export const Images = {
    // basket1 : require('./basket1.png'),
    // basket2 : require('./basket2.png'),
    // basket3 : require('./basket3.png'),
    // signin: require('./signin.png'),
    // cake: require('./cake.png'),
    // pager1: require('./Pager1.png'),
    // pager2: require('./Pager2.png'),
    // pager3: require('./Pager3.png'),
    profile: require('./profilepic.png'),
    // filter: require('./sort.png'),
    // banner: require('./banner.png'),
    // offer: require('./offer.png'),
    // deals: require('./Deals.png'),
    // plus: require('./plus.png'),
    // ginjer: require('./ginjer.png'),
    // tomato: require('./tomato.png'),
    back: require('./back.png'),
    // minus: require('./minus.png'),
    // calories: require('./Calories.png'),
    // star: require('./star.png'),
    // chat: require('./chat.png')
     };