export const SEARCH_TEXT = 'What do you looking for?';
export const WELCOME_TEXT = 'Welcome Back, ';
export const ENTER_INFO = 'Please type your information';
export const ENTER_EMAIL = 'Email address';
export const PASSWORD = 'Password';
export const NEW_USER = 'New user? ';
export const CREATE_ACCOUNT = 'Create an account';
export const ALREADY_ACCOUNT = 'Already have an account?';
export const LOG_IN = 'Login';
export const FULL_NAME = "Full name";
export const CREATE_ACC_BTN = 'Create Account'